import json
import os
import random

"""
Enhanced Movie Recommendation Database.
Loads 1000+ movies from 'movies_extended.json' (generated by imdb_importer.py).
Categorizes movies by 7 emotions and returns randomized sets of 12.
"""

EXTENDED_DATA_FILE = os.path.join(os.path.dirname(__file__), "movies_extended.json")

# Fallback basic dataset (if JSON is missing)
FALLBACK_MOVIES = {
    "happy": [
        {"title": "The Intouchables", "genre": "Comedy", "year": "2011", "rating": 8.5, "description": "Uplifting friendship.", "poster": "https://image.tmdb.org/t/p/w300/6B9bKzoUVqnPuqMl4xbFWRJJcFu.jpg"},
        {"title": "La La Land", "genre": "Musical", "year": "2016", "rating": 8.0, "description": "Romantic musical.", "poster": "https://image.tmdb.org/t/p/w300/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg"},
    ],
    "sad": [{"title": "The Pursuit of Happyness", "genre": "Drama", "year": "2006", "rating": 8.0, "description": "Heartfelt story.", "poster": "https://image.tmdb.org/t/p/w300/lP4JfxS19oGvEbFJEBuMUGg9M0T.jpg"}],
    "angry": [{"title": "John Wick", "action": "Action", "year": "2014", "rating": 7.4, "description": "Action fury.", "poster": "https://image.tmdb.org/t/p/w300/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg"}],
}

def load_extended_movies():
    """Loads the 1000+ movies from JSON."""
    if os.path.exists(EXTENDED_DATA_FILE):
        try:
            with open(EXTENDED_DATA_FILE, 'r', encoding='utf-8') as f:
                return json.load(f)
        except Exception as e:
            print(f"[MoviesDB] Error loading extended data: {e}")
    return FALLBACK_MOVIES

# Global cache
_cached_movies = load_extended_movies()

def get_movies_for_emotion(emotion: str, count: int = 12) -> list:
    """Return randomized movie list for a given emotion (Default 12)."""
    emotion = emotion.lower().strip()
    
    # Reload if empty (for dev)
    global _cached_movies
    if not _cached_movies:
        _cached_movies = load_extended_movies()
        
    movies = _cached_movies.get(emotion, [])
    
    # Fallback to neutral or any available if category empty
    if not movies:
        movies = _cached_movies.get("neutral", []) or _cached_movies.get("happy", [])
        
    # Shuffle and return requested count
    randomized = list(movies)
    random.shuffle(randomized)
    return randomized[:count]

def get_all_emotions() -> list:
    return ["happy", "sad", "angry", "fear", "surprise", "disgust", "neutral"]

EMOTION_META = {
    "happy":   {"icon": "😄", "color": "#FFD700", "label": "Happy",   "tip": "You're glowing! These 12 films are picked from our 1000+ library just for you."},
    "sad":     {"icon": "😢", "color": "#4A9EFF", "label": "Sad",     "tip": "It's okay to feel. These 12 heartfelt stories are here to keep you company."},
    "angry":   {"icon": "😠", "color": "#FF4136", "label": "Angry",   "tip": "Intense energy! Here are 12 high-octane films to match your mood."},
    "fear":    {"icon": "😨", "color": "#9B59B6", "label": "Fearful", "tip": "Suspense awaits. Dive into these 12 thrilling stories."},
    "neutral": {"icon": "😐", "color": "#95A5A6", "label": "Neutral", "tip": "Keeping it cool? Here are 12 thought-provoking films."},
    "disgust": {"icon": "🤢", "color": "#27AE60", "label": "Disgusted","tip": "Strong feelings. Explore these 12 dark, gripping cinematic tales."},
    "surprise":{"icon": "😮", "color": "#FF6B35", "label": "Surprised","tip": "Expecting the unexpected? These 12 films are full of twists!"},
}
